version: 0.0
os: linux
files:
  - source: /
    destination: /grounds
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
  ApplicationStart:
    - location: scripts/start_server.sh
